title: U.S. Office of Special Council
email: info@osc.gov
description: >-
  My agency rocks!

alert:
  enabled: false
  heading:
  text:

social-media:
  - service: twitter
    link: "https://x.com/US_OSC"
  - service: youtube
    link: "https://www.youtube.com/channel/UCx5trnGvaEc-tuytqNwafpA"

# Used to construct absolute URLs throughout the site
url: "https://www.MyAgency.gov"

# Digital Analytics Program (DAP) configuration
dap:
  agency:

# Site Navigation
secondary_navigation:
  - name: Contact us
    url: "/contact/"

footer_navigation:
  - name: Open Government
    url: "/resources/opengov"
  - name: Freedom of Information Act (FOIA)
    url: "/about/foia/index"
  - name: Artificial Intelligence (AI)
    url: "/resources/ai"
  - name: Privacy Program
    url: "/about/privacy/index"
  - name: No FEAR Act/EEO Reports
    url: "/resources/reports"
  - name: USA.gov
    url: https://usa.gov/
  - name: Accessibility
    url: "/about/policies/accessibility"
  - name: Careers
    url: "/about/opportunities"
  - name: Para Información En Español
    url: "/about/policies/espanol"


# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:
  api: https://api.gsa.gov/technology/searchgov/v2/results/i14y
  # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

  # Replace this with your search.gov account.
  affiliate: MyAgency

  # Replace this with your access key.
  access_key:
  # This renders the results within the page instead of sending to user to search.gov.
  inline: true

  # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
  # If you do not want to present search suggestions, set this value to false.
  suggestions: true
