## Comment out when doing local development
# backend:
#   name: github
#   repo: MyAgency/site
#   base_url: https://pages.cloud.gov
#   auth_endpoint: external/auth/github
#   preview_context: pages/build
#   branch: main
#   use_graphql: true

##
## Uncomment when doing local development on Netlify CMS
## Run `npx netlify-cms-proxy-server` to start working locally
## In another terminal, start the app with `npm start`
## See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
##

backend:
  name: git-gateway
local_backend: true

media_folder: img
public_folder: /img
publish_mode: editorial_workflow
logo_url: https://pages.cloud.gov/images/logos/pages-logo-blue.svg

editor:
  preview: false

collections:
  - name: "press-release"
    label: "Press Release"
    folder: "collections/press-release"
    create: true
    editor:
      preview: false
    slug: "{{date}}-{{slug}}"
    summary: "[{{date}}] {{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          date_format: "YYYY-MM-DD",
          default: "{{now}}",
          widget: "datetime",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options:
            [
              "hatch act",
              "prohibited personnel practices",
              "disclosure of wrongdoing",
              "general",
              "userra",
              "outreach training",
              "alternative dispute resolution",
            ],
        }
