## Comment out when doing local development
backend:
  name: github
  repo: OSC-OCIO/osc.gov
  base_url: https://pages.cloud.gov
  auth_endpoint: external/auth/github
  preview_context: pages/build
  branch: main
  use_graphql: true

##
## Uncomment when doing local development on Netlify CMS
## Run `npx netlify-cms-proxy-server` to start working locally
## In another terminal, start the app with `npm start`
## See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
##

# backend:
#   name: git-gateway
# local_backend: true

media_folder: img
public_folder: /img
publish_mode: editorial_workflow
logo_url: https://pages.cloud.gov/images/logos/pages-logo-blue.svg

editor:
  preview: false

collections:
  - name: "case"
    label: "Cases"
    label_singular: "Case"
    folder: "collections/case"
    create: true
    slug: "{{cases[0]}}{{cases[1] | ternary('--multi', '')}}"
    summary: "{{cases[0]}}{{cases[1] | ternary(' + additional cases', '')}}"
    fields:
      - label: "Source"
        name: "source"
        widget: "list"
        fields:
          - {
              label: "Agency",
              name: "agency",
              widget: "select",
              multiple: false,
              options:
                [
                  "Agriculture",
                  "Customs and Border Protection",
                  "Defense/Air Force",
                  "Defense/Army",
                  "Defense/Navy",
                  "Department of Defense",
                  "Education",
                  "Energy",
                  "Environmental Protection Agency",
                  "Federal Aviation Administration",
                  "General Services Administration",
                  "Health and Human Services",
                  "Homeland Security",
                  "Housing and Urban Development",
                  "Interior",
                  "Justice",
                  "Labor",
                  "Naval Supply Systems Command",
                  "Other/Independent Agency",
                  "Selective Service System",
                  "Social Security Administration",
                  "State",
                  "Transportation",
                  "Treasury",
                  "U.S. Air Force",
                  "U.S. Army",
                  "U.S. Navy",
                  "Veterans Affairs",
                ],
            }
          - {
              label: "Subagency",
              name: "subagency",
              widget: "select",
              multiple: false,
              required: false,
              options:
                [
                  "Agricultural Research Service",
                  "Assistant Secretary for Human Resources Management",
                  "Bureau of Alcohol, Tobacco, Firearms, and Explosives",
                  "Bureau of Land Management",
                  "Bureau of Prisons/Federal Prison System",
                  "Bureau of Safety and Environmental Enforcement",
                  "Centers for Medicare and Medicaid Services",
                  "Customs and Border Protection",
                  "Defense Health Agency",
                  "Department of Defense",
                  "Drug Enforcement Administration",
                  "Federal Aviation Administration",
                  "Federal Bureau of Investigation",
                  "Federal Emergency Management Agency",
                  "Federal Railroad Administration",
                  "Federal Student Aid",
                  "Forest Service",
                  "Homeland Security",
                  "Immigration and Customs Enforcement",
                  "Internal Revenue Service",
                  "Mine Safety and Health Administration",
                  "Office of the Chief Financial Officer",
                  "Office of the Inspector General",
                  "Office of the Under Secretary",
                  "Transportation",
                  "Transportation Security Administration",
                  "U.S. Army",
                  "U.S. Army Aviation and Missile Command",
                  "U.S. Marshals Service",
                  "U.S. Navy",
                  "Veterans Health Administration",
                ],
            }
      - label: "Case(s)"
        name: "cases"
        widget: "list"
        allow_add: true
        summary: "{{fields.case}}"
        field: { label: Case Number, name: case, widget: string }
      - label: "Location(s)"
        name: "locations"
        widget: "list"
        allow_add: true
        summary: "{{fields.location}}"
        field: { label: "Location", name: location, widget: string }
      - label: "Result(s)"
        name: "results"
        widget: "select"
        multiple: true
        options:
          [
            "Agency takes systemic corrective action after OSC invovlement",
            "Changes in agency rules, regulations, policy or practices",
            "Cost savings to the government and/or accountability",
            "Disciplinary action against any employee",
            "Improved health and/or safety",
            "Partially substantiated",
            "Referral of criminal matter to the Attorney General",
            "Special Counsel found report not reasonable",
            "Substantiated",
            "Totally unsubstantiated",
            "Unsubstantiated but led to agency changes",
            "Other actions",
          ]
      - {
          label: "Date Closed",
          name: "date",
          date_format: "YYYY-MM-DD",
          widget: "datetime",
        }
      - label: "File(s)"
        name: "files"
        widget: "list"
        summary: "{{fields.label}}"
        fields:
          - { label: Label, name: label, widget: string }
          - { label: Link, name: href, widget: string }
  - name: "press-release"
    label_singular: "Press Release"
    label: "Press Release"
    folder: "collections/press-release"
    create: true
    slug: "{{date}}-{{slug}}"
    summary: "[{{date}}] {{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          date_format: "YYYY-MM-DD",
          default: "{{now}}",
          widget: "datetime",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options:
            [
              {
                label: "Alternative Dispute Resolution",
                value: "alternative dispute resolution",
              },
              {
                label: "Disclosure of Wrongdoing",
                value: "disclosure of wrongdoing",
              },
              { label: "General", value: "general" },
              { label: "Hatch Act", value: "hatch act" },
              { label: "Outreach Training", value: "outreach training" },
              {
                label: "Prohibited Personnel Practices",
                value: "prohibited personnel practices",
              },
              { label: "USERRA", value: "userra" },
            ],
        }
  - label: Homepage
    name: homepage
    files:
      - label: Home
        name: home
        file: "pages/index.md"
        create: false
        fields:
          - label: Hero Section
            name: hero
            widget: object
            required: false
            fields:
              - { label: Header, name: header, widget: string }
              - { label: Body, name: body, widget: string }
              - label: "Button 1 (Left)"
                name: "button_left"
                widget: "object"
                required: false
                fields:
                  - { label: Text, name: text, widget: string }
                  - { label: Link, name: link, widget: string }
              - label: "Button 2 (Right)"
                name: "button_right"
                widget: "object"
                required: false
                fields:
                  - { label: Text, name: text, widget: string }
                  - { label: Link, name: link, widget: string }
              - label: "Hero Image"
                name: "hero_image"
                widget: "object"
                required: false
                fields:
                  - { label: Image, name: image, widget: image }
                  - { label: "Alt text", name: "alt_text", widget: "string" }
          - label: Agency Highlights
            name: highlights
            widget: list
            min: 3
            max: 3
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string" }
              - { label: "Button Text", name: "cta_text", widget: "string" }
              - { label: "Button Link", name: "cta_url", widget: "string" }
          - label: Featured Video
            name: video
            widget: object
            fields:
              - { label: Header, name: header, widget: string }
              - { label: Video Title, name: title, widget: string }
              - { label: "Body", name: "body", widget: "string" }
              - { label: "Video Link", name: "url", widget: "string" }
              - { label: "Button Text", name: "button_text", widget: "string" }
              - { label: "Button Link", name: "button_url", widget: "string" }
